# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'EasyPermissionX/Camera'

  # 添加我们的补丁文件
  pod 'SentryCrashPatch', :path => 'fix_headers', :inhibit_warnings => true

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      
      # 给Sentry添加特定的编译定义以解决C++异常监控问题
      if target.name == 'Sentry'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        # 添加所需的定义，但不完全禁用功能
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'SENTRY_BUILD_WITHOUT_CPP_EXCEPTION=1'
        
        # 修改编译标志以处理macOS 10.15+ SDK中的ucontext64_t问题
        config.build_settings['OTHER_CFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=incomplete-implementation'
        config.build_settings['OTHER_CFLAGS'] << '-Wno-error=strict-prototypes'
      end
      
      # 支持Apple Silicon模拟器
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
      config.build_settings['VALID_ARCHS'] = 'arm64 arm64e x86_64'
      config.build_settings['ARCHS[sdk=iphonesimulator*]'] = 'arm64 x86_64'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = 'armv7'
    end
  end
end
